Repository PUNCH-Cyber/stoq, pull requests merged in 2020-03, with the labels that each got.

#137 Stoq config getjson
  stoq/helpers/__init__.py
  stoq/tests/data/config.cfg
  stoq/tests/test_helpers.py
Labels: enhancement

#141 Fix documentation
  stoq/core.py
Labels: documentation

#145 Fix stoq cmd line to properly parse `plugin-opts` and `request-source`
  CHANGELOG.md
  stoq/__init__.py
  stoq/cli.py
Labels: bug

#146 Fixed typo, and added space before code (in core.py) so that it gets …
  docs/dev/upgrading_plugins.rst
  stoq/core.py
Labels: documentation
